### ISSUE TITLE
[Deploy] RequestError: Error: socket hang up

### ISSUE THREAD

**Issue by noranuko13** [noranuko13/hatena-theme-base#1]
## 問題内容
- デプロイが異常終了する
  - CircleCI, ローカル共に再現

## 再現手順
```
$ node deploy.js
resolve: RequestError: Error: socket hang up
```

## 期待される結果
- デプロイが正常終了する

### 問題箇所
- 『テーマストア編集画面を表示する』で起きている。
- ブラウザでURLを直打ちすると正常にアクセスができる。
- 対象のURLが
  - 『'https://blog.hatena.ne.jp/-/store/theme/' + themeUuid』では正常にアクセスできる。
  - 『'https://blog.hatena.ne.jp/-/store/theme/' + themeUuid + '/edit'』には正常にアクセスできない。
- ログイン自体は出来ている。

### ログ
```
   at new RequestError (C:\Projects\hatena-theme-base\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Projects\hatena-theme-base\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Projects\hatena-theme-base\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Projects\hatena-theme-base\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (C:\Projects\hatena-theme-base\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:327:22)
    at TLSSocket.socketOnEnd (_http_client.js:453:9)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

### curl
- HTTPステータスコード
```
$ curl -LI "https://blog.hatena.ne.jp/-/store/theme/《themeUuid》" -o /dev/null -w '%{http_code}\n' -s
404
$ curl -LI "https://blog.hatena.ne.jp/-/store/theme/《themeUuid》/edit" -o /dev/null -w '%{http_code}\n' -s
000
```
- ちなみにブラウザから未ログインの状態でアクセスすると、
  - テーマ詳細画面にアクセスすると『404 Theme Not Found』画面に遷移する。
  - テーマ編集画面にアクセスすると『ログイン』画面に遷移する。

- curl -v
```
$ curl -v "https://blog.hatena.ne.jp/-/store/theme/《themeUuid》/edit"
（前略）
*  SSL certificate verify ok.
} [5 bytes data]
> GET /-/store/theme/《themeUuid》/edit HTTP/1.1
> Host: blog.hatena.ne.jp
> User-Agent: curl/7.65.1
> Accept: */*
>
{ [5 bytes data]
* TLSv1.2 (IN), TLS alert, close notify (256):
{ [2 bytes data]
* Empty reply from server
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, close notify (256):
} [2 bytes data]
curl: (52) Empty reply from server
```

### 備考
- サーバー側の問題だと厳しいかもしれない。
- ヘッドレスブラウザではどうか。

**Comment by noranuko13** [comment]
- 2020/06/15 11:26 試したところ
```
$ curl -LI "https://blog.hatena.ne.jp/-/store/theme/《themeUuid》" -o /dev/null -w '%{http_code}\n' -s
404
$ curl -LI "https://blog.hatena.ne.jp/-/store/theme/《themeUuid》/edit" -o /dev/null -w '%{http_code}\n' -s
403
```

```
node deploy.js
resolve: StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

**Comment by noranuko13** [comment]
7968644 [Puppeteer](https://pptr.dev/) を使う方向で修正中。
```page.$eval```へ値を渡す書き方がややこしい。詰まったのは恐らくここだけ。
```JavaScript
await page.$eval(selector, (e, content) => e.value = content, content);
```
